jobs:
  lint:
    defaults:
      run:
        working-directory: tools/vscode_sql_extraction
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - continue-on-error: true
      env:
        cache-name: cache-node-modules
      name: Cache node modules
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json')
          }}
        path: ~/.npm
        restore-keys: '${{ runner.os }}-build-${{ env.cache-name }}-

          ${{ runner.os }}-build-

          ${{ runner.os }}-

          '
    - continue-on-error: true
      name: Install dependencies
      run: npm install
    - continue-on-error: true
      name: Run linter/checks
      run: npm run check
  test:
    defaults:
      run:
        working-directory: tools/vscode_sql_extraction
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - continue-on-error: true
      env:
        cache-name: cache-node-modules
      name: Cache node modules
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json')
          }}
        path: ~/.npm
        restore-keys: '${{ runner.os }}-build-${{ env.cache-name }}-

          ${{ runner.os }}-build-

          ${{ runner.os }}-

          '
    - continue-on-error: true
      name: Install dependencies
      run: npm install
    - continue-on-error: true
      name: Run tests
      uses: GabrielBB/xvfb-action@v1.2
      with:
        run: npm test
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
name: VS Code Extension for SQL Extraction
on:
  repository_dispatch:
    types: trigger-ga___vscode-sql-extraction.yml
